apiVersion: v1
kind: ConfigMap
metadata:
  name: cuneiform-config
  namespace: galaxy
data:
  config.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "raft" {
      path    = "/openbao/data"
      node_id = "node1"
    }

    api_addr = "http://cuneiform-service.galaxy.svc.cluster.local:8200"
    cluster_addr = "http://cuneiform-service.galaxy.svc.cluster.local:8201"
