apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: galaxy
  labels:
    app: garage
data:
  garage.toml: |
    metadata_dir = "/meta"
    data_dir = "/data"
    
    replication_mode = "none"
    
    compression_level = 1
    
    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "127.0.0.1:3901"
    rpc_secret = "change-this-secret-to-something-random-32chars"
    
    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.localhost"
    
    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.localhost"
    
    [admin]
    api_bind_addr = "[::]:3903"
