apiVersion: v1
kind: ConfigMap
metadata:
  name: ouroboros-config
  namespace: galaxy
data:
  WOODPECKER_OPEN: "true"
  WOODPECKER_ORGS: "pinwheel-labs"
  WOODPECKER_BACKEND: "docker"
  WOODPECKER_LOG_LEVEL: "info"
  WOODPECKER_GITHUB: "true"
