apiVersion: v1
kind: ConfigMap
metadata:
  name: ouroboros-config
  namespace: galaxy
data:
  WOODPECKER_OPEN: "true"
  WOODPECKER_ORGS: "pinwheel-labs"
  WOODPECKER_BACKEND: "kubernetes"
  WOODPECKER_BACKEND_K8S_NAMESPACE: "galaxy"
  WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
  WOODPECKER_BACKEND_K8S_SERVICE_ACCOUNT: "ouroboros-deployer"
  WOODPECKER_BACKEND_K8S_SERVICE_ACCOUNT_NAME: "ouroboros-deployer"
  WOODPECKER_LOG_LEVEL: "info"
  WOODPECKER_GITHUB: "true"
