apiVersion: apps/v1
kind: Deployment
metadata:
  name: noctis
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: noctis
  template:
    metadata:
      labels:
        name: noctis
    spec:
      serviceAccountName: noctis
      containers:
        - name: noctis
          image: edrodefeld/noctis
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: noctis-config
            - secretRef:
                name: noctis-env-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
