apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noctis-ingress
  namespace: galaxy
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - noctis.pinwheel.fan
      secretName: noctis-tls
  rules:
    - host: noctis.pinwheel.fan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noctis-prefect-service
                port:
                  number: 4200

