apiVersion: v1
kind: Service
metadata:
  name: noctis-prefect-service
  namespace: galaxy
spec:
  selector:
    name: noctis-prefect-server
  ports:
    - name: http
      port: 4200
      targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: noctis-postgres-service
  namespace: galaxy
spec:
  selector:
    name: noctis-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

