apiVersion: apps/v1
kind: Deployment
metadata:
  name: doppler
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: doppler
  template:
    metadata:
      labels:
        name: doppler
    spec:
      serviceAccountName: doppler
      containers:
        - name: doppler
          image: edrodefeld/doppler
          imagePullPolicy: Always
          ports:
            - containerPort: 1323
          envFrom:
            # Load non-sensitive configuration
            - configMapRef:
                name: doppler-config
            # Load secrets
            - secretRef:
                name: doppler-env-secrets
          volumeMounts:
            - mountPath: /app/data
              name: doppler-data
          livenessProbe:
            httpGet:
              path: /livez
              port: 1323
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 1323
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: doppler-data
          persistentVolumeClaim:
            claimName: doppler-volume-claim
