apiVersion: v1
kind: ConfigMap
metadata:
  name: parakeet-config
  namespace: galaxy
data:
  PHX_SERVER: "true"
  PHX_HOST: "parakeet.pinwheel.fan"
  PORT: "4000"
  POOL_SIZE: "5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parakeet-postgres-config
  namespace: galaxy
data:
  POSTGRES_USER: "parakeet"
  POSTGRES_DB: "parakeet_prod"
  PGDATA: "/var/lib/postgresql/data/pgdata"
