apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-config
  namespace: galaxy
data:
  # PostgreSQL configuration
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  PGDATA: "/var/lib/postgresql/data/pgdata"

