apiVersion: apps/v1
kind: Deployment
metadata:
  name: augur
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: augur
  template:
    metadata:
      labels:
        name: augur
    spec:
      containers:
        - name: augur
          image: edrodefeld/augur
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: augur-config
            - secretRef:
                name: augur-env-secrets
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
